# Generated by Django 5.1.15 on 2026-02-18 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorldState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_consistency', models.FloatField(default=0.5)),
                ('stress_level', models.FloatField(default=0.5)),
                ('breakthroughs', models.PositiveIntegerField(default=0)),
                ('neglect', models.FloatField(default=0.0)),
                ('terrain_seed', models.PositiveIntegerField(default=42)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='world_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
