# Generated by Django 5.1.15 on 2026-02-18 15:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio'), ('video', 'Video'), ('question', 'Question')], default='text', max_length=16)),
                ('content_text', models.TextField(blank=True, default='')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='entries/')),
                ('mood', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileAggregate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_profile', models.JSONField(blank=True, default=dict)),
                ('shadow_profile', models.JSONField(blank=True, default=dict)),
                ('value_gap_report', models.JSONField(blank=True, default=dict)),
                ('future_self_thread', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_aggregate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
